<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
// Exit if accessed directly
/**
 * Room views
 *
 * @return array roomviews
 */
function staylodgic_get_room_views() {
	$roomviews = array(
		'CityView'          => __( 'City View', 'staylodgic' ),
		'SeaView'           => __( 'Sea View', 'staylodgic' ),
		'MountainView'      => __( 'Mountain View', 'staylodgic' ),
		'GardenView'        => __( 'Garden View', 'staylodgic' ),
		'PoolView'          => __( 'Pool View', 'staylodgic' ),
		'RiverView'         => __( 'River View', 'staylodgic' ),
		'LakeView'          => __( 'Lake View', 'staylodgic' ),
		'ForestView'        => __( 'Forest View', 'staylodgic' ),
		'CourtyardView'     => __( 'Courtyard View', 'staylodgic' ),
		'Beachfront'        => __( 'Beachfront', 'staylodgic' ),
		'ParkView'          => __( 'Park View', 'staylodgic' ),
		'CountrysideView'   => __( 'Countryside View', 'staylodgic' ),
		'SunsetView'        => __( 'Sunset View', 'staylodgic' ),
		'SkylineView'       => __( 'Skyline View', 'staylodgic' ),
		'HarborView'        => __( 'Harbor View', 'staylodgic' ),
		'HistoricView'      => __( 'Historic View', 'staylodgic' ),
		'PanoramicView'     => __( 'Panoramic View', 'staylodgic' ),
		'VineyardView'      => __( 'Vineyard View', 'staylodgic' ),
		'PoolsideView'      => __( 'Poolside View', 'staylodgic' ),
		'WildlifeView'      => __( 'Wildlife View', 'staylodgic' ),
		'SkiSlopesView'     => __( 'Ski Slopes View', 'staylodgic' ),
		'ThemeParkView'     => __( 'Theme Park View', 'staylodgic' ),
		'SportsStadiumView' => __( 'Sports Stadium View', 'staylodgic' ),
		'WaterfrontView'    => __( 'Waterfront View', 'staylodgic' ),
		'ForestCabinView'   => __( 'Forest Cabin View', 'staylodgic' ),
		'ArtisticView'      => __( 'Artistic View', 'staylodgic' ),
		'RooftopView'       => __( 'Rooftop View', 'staylodgic' ),
		'BalconyView'       => __( 'Balcony View', 'staylodgic' ),
		'DesertView'        => __( 'Desert View', 'staylodgic' ),
		'LagoonView'        => __( 'Lagoon View', 'staylodgic' ),
		'SideSeaView'       => __( 'Side Sea-view', 'staylodgic' ),
	);
	return $roomviews;
}

/**
 * Room facilities
 *
 * @return array roomfacilities
 */
function staylodgic_get_room_facitilies() {
	$roomfacilities = array(
		'AC'          => __( 'Air Conditioning', 'staylodgic' ),
		'TV'          => __( 'Television', 'staylodgic' ),
		'WiFi'        => __( 'Free WiFi', 'staylodgic' ),
		'WC'          => __( 'Private Bathroom', 'staylodgic' ),
		'Balcony'     => __( 'Balcony', 'staylodgic' ),
		'Minibar'     => __( 'Minibar', 'staylodgic' ),
		'Safe'        => __( 'In-room Safe', 'staylodgic' ),
		'RoomService' => __( 'Room Service', 'staylodgic' ),
		'Kitchenette' => __( 'Kitchenette', 'staylodgic' ),
		'Bathtub'     => __( 'Bathtub', 'staylodgic' ),
		'Jacuzzi'     => __( 'Jacuzzi', 'staylodgic' ),
		'Gym'         => __( 'Fitness Gym', 'staylodgic' ),
		'Spa'         => __( 'Spa Facilities', 'staylodgic' ),
		'Pool'        => __( 'Swimming Pool', 'staylodgic' ),
		'BeachAccess' => __( 'Beach Access', 'staylodgic' ),
		'Parking'     => __( 'Parking Area', 'staylodgic' ),
		'PetFriendly' => __( 'Pet Friendly', 'staylodgic' ),
		'Conference'  => __( 'Conference Room', 'staylodgic' ),
	);
	return $roomfacilities;
}

/**
 * Room amenities
 *
 * @return array amenities
 */
function staylodgic_get_hotel_amenities() {
	$amenities = array(
		'1'   => __( '24-hour front desk', 'staylodgic' ),
		'5'   => __( 'Air conditioning', 'staylodgic' ),
		'7'   => __( 'ATM on site', 'staylodgic' ),
		'8'   => __( 'Babysitting', 'staylodgic' ),
		'9'   => __( 'BBQ/Picnic area', 'staylodgic' ),
		'14'  => __( 'Library', 'staylodgic' ),
		'15'  => __( 'Car rental', 'staylodgic' ),
		'16'  => __( 'Casino', 'staylodgic' ),
		'22'  => __( 'Concierge desk', 'staylodgic' ),
		'26'  => __( 'Currency exchange', 'staylodgic' ),
		'33'  => __( 'Elevators', 'staylodgic' ),
		'35'  => __( 'Fitness Center', 'staylodgic' ),
		'36'  => __( 'Express Check-in/Check-out', 'staylodgic' ),
		'41'  => __( 'Airport shuttle (free)', 'staylodgic' ),
		'44'  => __( 'Game room', 'staylodgic' ),
		'45'  => __( 'Souvenir/Gift Shop', 'staylodgic' ),
		'49'  => __( 'Heated pool', 'staylodgic' ),
		'50'  => __( 'Housekeeping - daily', 'staylodgic' ),
		'53'  => __( 'Indoor parking', 'staylodgic' ),
		'54'  => __( 'Indoor pool', 'staylodgic' ),
		'55'  => __( 'Jacuzzi (Hot Tub)', 'staylodgic' ),
		'60'  => __( 'Evening Entertainment', 'staylodgic' ),
		'61'  => __( 'Massage', 'staylodgic' ),
		'62'  => __( 'Nightclub/DJ', 'staylodgic' ),
		'66'  => __( 'Outdoor pool', 'staylodgic' ),
		'76'  => __( 'Restaurant', 'staylodgic' ),
		'77'  => __( 'Room service', 'staylodgic' ),
		'78'  => __( 'Safe', 'staylodgic' ),
		'79'  => __( 'Sauna', 'staylodgic' ),
		'81'  => __( 'Shoeshine', 'staylodgic' ),
		'83'  => __( 'Solarium', 'staylodgic' ),
		'86'  => __( 'Turkish/Steam Bath', 'staylodgic' ),
		'91'  => __( 'Tour Desk', 'staylodgic' ),
		'96'  => __( 'Dry cleaning', 'staylodgic' ),
		'97'  => __( 'Valet parking', 'staylodgic' ),
		'98'  => __( 'Vending Machine (snacks)', 'staylodgic' ),
		'116' => __( 'Accessible parking', 'staylodgic' ),
		'122' => __( 'Shops (on site)', 'staylodgic' ),
		'149' => __( 'Grocery shopping service available', 'staylodgic' ),
		'165' => __( 'Bar', 'staylodgic' ),
		'168' => __( 'Laundry', 'staylodgic' ),
		'173' => __( 'Breakfast', 'staylodgic' ),
		'186' => __( 'Street parking', 'staylodgic' ),
		'193' => __( 'Playground', 'staylodgic' ),
		'197' => __( 'Lockers', 'staylodgic' ),
		'198' => __( 'Non-smoking rooms', 'staylodgic' ),
		'202' => __( 'Bicycle rentals', 'staylodgic' ),
		'228' => __( 'Business center', 'staylodgic' ),
		'230' => __( 'Secured parking', 'staylodgic' ),
		'233' => __( 'Tennis court', 'staylodgic' ),
		'234' => __( 'Water Sport Facilities (on site)', 'staylodgic' ),
		'236' => __( 'Golf Course (within 2 miles)', 'staylodgic' ),
		'237' => __( 'Horseback riding', 'staylodgic' ),
		'239' => __( 'Beachfront', 'staylodgic' ),
		'242' => __( 'Heating', 'staylodgic' ),
		'262' => __( 'Shared Kitchen', 'staylodgic' ),
		'269' => __( 'Meeting/Banquet Facilities', 'staylodgic' ),
		'272' => __( 'Skiing', 'staylodgic' ),
		'282' => __( 'Airport shuttle service (surcharge)', 'staylodgic' ),
		'283' => __( 'Baggage Storage', 'staylodgic' ),
		'292' => __( 'Newspaper', 'staylodgic' ),
		'310' => __( 'Hypoallergenic room available', 'staylodgic' ),
		'312' => __( 'All Spaces Non-Smoking (public and private)', 'staylodgic' ),
		'316' => __( 'Electric vehicle charging station', 'staylodgic' ),
		'327' => __( 'Events ticket service', 'staylodgic' ),
		'342' => __( 'Snack bar', 'staylodgic' ),
	);

	return $amenities;
}

/**
 * Property amenities
 *
 * @return array amenities
 */
function staylodgic_get_hotel_extended_amenities() {
	$amenities = array(
		'5000' => __( 'Breakfast in the room', 'staylodgic' ),
		'5001' => __( 'Public transport tickets', 'staylodgic' ),
		'5002' => __( 'Bikes available (free)', 'staylodgic' ),
		'5003' => __( 'Outdoor furniture', 'staylodgic' ),
		'5004' => __( 'Outdoor fireplace', 'staylodgic' ),
		'5005' => __( 'Garden', 'staylodgic' ),
		'5006' => __( 'Terrace', 'staylodgic' ),
		'5007' => __( 'Sun terrace', 'staylodgic' ),
		'5008' => __( 'Chapel/shrine', 'staylodgic' ),
		'5009' => __( 'Shared lounge/TV area', 'staylodgic' ),
		'5010' => __( 'Ironing service', 'staylodgic' ),
		'5011' => __( 'Trouser press', 'staylodgic' ),
		'5012' => __( 'Designated smoking area', 'staylodgic' ),
		'5013' => __( 'Pet basket', 'staylodgic' ),
		'5014' => __( 'Pet bowls', 'staylodgic' ),
		'5015' => __( 'Beach', 'staylodgic' ),
		'5016' => __( 'Bowling', 'staylodgic' ),
		'5017' => __( 'Darts', 'staylodgic' ),
		'5018' => __( 'Fishing', 'staylodgic' ),
		'5020' => __( 'Hiking', 'staylodgic' ),
		'5021' => __( 'Minigolf', 'staylodgic' ),
		'5022' => __( 'Snorkeling', 'staylodgic' ),
		'5023' => __( 'Squash', 'staylodgic' ),
		'5024' => __( 'Windsurfing', 'staylodgic' ),
		'5025' => __( 'Billiard', 'staylodgic' ),
		'5026' => __( 'Table tennis', 'staylodgic' ),
		'5027' => __( 'Canoeing', 'staylodgic' ),
		'5028' => __( 'Ski-to-door access', 'staylodgic' ),
		'5029' => __( 'Diving', 'staylodgic' ),
		'5030' => __( 'Tennis equipment', 'staylodgic' ),
		'5031' => __( 'Badminton equipment', 'staylodgic' ),
		'5032' => __( 'Cycling', 'staylodgic' ),
		'5033' => __( 'Ski storage', 'staylodgic' ),
		'5034' => __( 'Ski school', 'staylodgic' ),
		'5035' => __( 'Ski equipment hire (on site)', 'staylodgic' ),
		'5036' => __( 'Ski pass vendor', 'staylodgic' ),
		'5037' => __( 'Private beach area', 'staylodgic' ),
		'5039' => __( 'Rooms/Facilities for Disabled', 'staylodgic' ),
		'5040' => __( 'Hairdresser/Beautician', 'staylodgic' ),
		'5041' => __( 'Family Rooms', 'staylodgic' ),
		'5042' => __( 'VIP Room Facilities', 'staylodgic' ),
		'5043' => __( 'Bridal Suite', 'staylodgic' ),
		'5044' => __( 'Spa & Wellness Centre', 'staylodgic' ),
		'5045' => __( 'Karaoke', 'staylodgic' ),
		'5046' => __( 'Soundproof rooms', 'staylodgic' ),
		'5047' => __( 'Packed Lunches', 'staylodgic' ),
		'5048' => __( 'Ticket service', 'staylodgic' ),
		'5049' => __( 'Entertainment Staff', 'staylodgic' ),
		'5050' => __( 'Private Check-in/Check-out', 'staylodgic' ),
		'5051' => __( 'Special Diet Menus (on request)', 'staylodgic' ),
		'5052' => __( 'Vending Machine (drinks)', 'staylodgic' ),
		'5053' => __( 'Hot Spring Bath', 'staylodgic' ),
		'5054' => __( 'Kids\' club', 'staylodgic' ),
		'5055' => __( 'Minimarket on site', 'staylodgic' ),
		'5056' => __( 'Water park', 'staylodgic' ),
		'5057' => __( 'Adult only', 'staylodgic' ),
		'5058' => __( 'Open-air bath', 'staylodgic' ),
		'5059' => __( 'Public bath', 'staylodgic' ),
		'5060' => __( 'Water slide', 'staylodgic' ),
		'5061' => __( 'Board games/puzzles', 'staylodgic' ),
		'5062' => __( 'Book/DVD/Music library for children', 'staylodgic' ),
		'5063' => __( 'Indoor play area', 'staylodgic' ),
		'5064' => __( 'Kids\' outdoor play equipment', 'staylodgic' ),
		'5065' => __( 'Baby safety gates', 'staylodgic' ),
		'5066' => __( 'Children television networks', 'staylodgic' ),
		'5067' => __( 'Kid meals', 'staylodgic' ),
		'5068' => __( 'Kid-friendly buffet', 'staylodgic' ),
		'5069' => __( 'Pool towels', 'staylodgic' ),
		'5070' => __( 'Wine/Champagne', 'staylodgic' ),
		'5071' => __( 'Bottle of water', 'staylodgic' ),
		'5072' => __( 'Fruits', 'staylodgic' ),
		'5073' => __( 'Chocolate/Cookies', 'staylodgic' ),
		'5074' => __( 'Strollers', 'staylodgic' ),
		'5075' => __( 'On-site coffee house', 'staylodgic' ),
		'5076' => __( 'Sun loungers or beach chairs', 'staylodgic' ),
		'5077' => __( 'Sun umbrellas', 'staylodgic' ),
		'5078' => __( 'Picnic area', 'staylodgic' ),
		'5079' => __( 'Beauty Services', 'staylodgic' ),
		'5080' => __( 'Spa Facilities', 'staylodgic' ),
		'5081' => __( 'Steam room', 'staylodgic' ),
		'5082' => __( 'Spa lounge/relaxation area', 'staylodgic' ),
		'5083' => __( 'Foot bath', 'staylodgic' ),
		'5084' => __( 'Spa/wellness packages', 'staylodgic' ),
		'5085' => __( 'Massage chair', 'staylodgic' ),
		'5086' => __( 'Fitness', 'staylodgic' ),
		'5087' => __( 'Yoga classes', 'staylodgic' ),
		'5088' => __( 'Fitness classes', 'staylodgic' ),
		'5089' => __( 'Personal trainer', 'staylodgic' ),
		'5090' => __( 'Fitness/spa locker rooms', 'staylodgic' ),
		'5091' => __( 'Kids pool', 'staylodgic' ),
		'5092' => __( 'Shuttle Service', 'staylodgic' ),
		'5093' => __( 'Temporary art galleries', 'staylodgic' ),
		'5094' => __( 'Pub crawls', 'staylodgic' ),
		'5095' => __( 'Stand-up comedy', 'staylodgic' ),
		'5096' => __( 'Movie nights', 'staylodgic' ),
		'5097' => __( 'Walking tours', 'staylodgic' ),
		'5098' => __( 'Bike tours', 'staylodgic' ),
		'5099' => __( 'Themed dinner nights', 'staylodgic' ),
		'5100' => __( 'Happy hour', 'staylodgic' ),
		'5101' => __( 'Tour or class about local culture', 'staylodgic' ),
		'5102' => __( 'Cooking class', 'staylodgic' ),
		'5103' => __( 'Live music/performance', 'staylodgic' ),
		'5104' => __( 'Live sports events (broadcast)', 'staylodgic' ),
		'5105' => __( 'Archery', 'staylodgic' ),
		'5106' => __( 'Aerobics', 'staylodgic' ),
		'5107' => __( 'Bingo', 'staylodgic' ),
		'5108' => __( 'Ski Shuttle', 'staylodgic' ),
		'5109' => __( 'Outdoor Swimming Pool (all year)', 'staylodgic' ),
		'5110' => __( 'Outdoor Swimming Pool (seasonal)', 'staylodgic' ),
		'5111' => __( 'Indoor Swimming Pool (all year)', 'staylodgic' ),
		'5112' => __( 'Indoor Swimming Pool (seasonal)', 'staylodgic' ),
		'5113' => __( 'Swimming pool toys', 'staylodgic' ),
		'5114' => __( 'Rooftop pool', 'staylodgic' ),
		'5115' => __( 'Infinity pool', 'staylodgic' ),
		'5116' => __( 'Pool with view', 'staylodgic' ),
		'5117' => __( 'Salt-water pool', 'staylodgic' ),
		'5118' => __( 'Plunge pool', 'staylodgic' ),
		'5119' => __( 'Pool cover', 'staylodgic' ),
		'5120' => __( 'Fence around pool', 'staylodgic' ),
		'5121' => __( 'Airport Shuttle (surcharge)', 'staylodgic' ),
		'5122' => __( 'Property is wheelchair accessible', 'staylodgic' ),
		'5123' => __( 'Toilet with grab rails', 'staylodgic' ),
		'5124' => __( 'Higher-level toilet', 'staylodgic' ),
		'5125' => __( 'Low bathroom sink', 'staylodgic' ),
		'5126' => __( 'Bathroom emergency pull cord', 'staylodgic' ),
		'5127' => __( 'Visual aids: Braille', 'staylodgic' ),
		'5128' => __( 'Visual aids: Tactile Signs', 'staylodgic' ),
		'5129' => __( 'Auditory Guidance', 'staylodgic' ),
		'5130' => __( 'Back massage', 'staylodgic' ),
		'5131' => __( 'Neck massage', 'staylodgic' ),
		'5132' => __( 'Foot massage', 'staylodgic' ),
		'5133' => __( 'Couples massage', 'staylodgic' ),
		'5134' => __( 'Head massage', 'staylodgic' ),
		'5135' => __( 'Hand massage', 'staylodgic' ),
		'5136' => __( 'Full body massage', 'staylodgic' ),
		'5137' => __( 'Facial treatments', 'staylodgic' ),
		'5138' => __( 'Waxing services', 'staylodgic' ),
		'5139' => __( 'Makeup services', 'staylodgic' ),
		'5140' => __( 'Hair treatments', 'staylodgic' ),
		'5141' => __( 'Manicure', 'staylodgic' ),
		'5142' => __( 'Pedicure', 'staylodgic' ),
		'5143' => __( 'Haircut', 'staylodgic' ),
		'5144' => __( 'Hair coloring', 'staylodgic' ),
		'5145' => __( 'Hair styling', 'staylodgic' ),
		'5146' => __( 'Body Treatments', 'staylodgic' ),
		'5147' => __( 'Body scrub', 'staylodgic' ),
		'5148' => __( 'Body wrap', 'staylodgic' ),
		'5149' => __( 'Light therapy', 'staylodgic' ),
		'5150' => __( 'Shuttle Service (free)', 'staylodgic' ),
		'5151' => __( 'Shuttle Service (surcharge)', 'staylodgic' ),
		'5152' => __( 'Swimming pool', 'staylodgic' ),
		'5156' => __( 'Property removed all, or never offered, single-use plastic toiletries', 'staylodgic' ),
		'5157' => __( 'Towels Changed Upon Request', 'staylodgic' ),
		'5158' => __( '24-hour security', 'staylodgic' ),
		'5159' => __( 'Security alarm', 'staylodgic' ),
		'5160' => __( 'Smoke alarms', 'staylodgic' ),
		'5161' => __( 'CCTV in common areas', 'staylodgic' ),
		'5162' => __( 'CCTV outside property', 'staylodgic' ),
		'5163' => __( 'Fire extinguishers', 'staylodgic' ),
		'5164' => __( 'Key access', 'staylodgic' ),
		'5165' => __( 'Key card access', 'staylodgic' ),
		'5166' => __( 'Carbon monoxide detector', 'staylodgic' ),
		'5167' => __( 'Carbon monoxide source', 'staylodgic' ),
		'5168' => __( 'Property removed all, or never offered, plastic stirrers', 'staylodgic' ),
		'5169' => __( 'Property removed all, or never offered, plastic straws', 'staylodgic' ),
		'5170' => __( 'Property removed all, or never offered, plastic cups', 'staylodgic' ),
		'5171' => __( 'Property removed all, or never offered, plastic water bottles', 'staylodgic' ),
		'5172' => __( 'Property removed all, or never offered, plastic bottles for non-water drinks', 'staylodgic' ),
		'5173' => __( 'Property removed all, or never offered, plastic cutlery and tableware', 'staylodgic' ),
		'5174' => __( 'Keycard for room electricity', 'staylodgic' ),
		'5175' => __( 'Opt-out from daily room cleaning', 'staylodgic' ),
		'5176' => __( 'Refillable water stations', 'staylodgic' ),
		'5177' => __( 'Bike rental', 'staylodgic' ),
		'5178' => __( 'Bike parking', 'staylodgic' ),
		'5179' => __( 'Use of cleaning chemicals that are effective against Coronavirus', 'staylodgic' ),
		'5180' => __( 'Linens, towels, and laundry washed in accordance with local authorities guidelines', 'staylodgic' ),
		'5181' => __( 'Guest accommodation is disinfected between stays', 'staylodgic' ),
		'5182' => __( 'Guest accommodation sealed after cleaning', 'staylodgic' ),
		'5183' => __( 'Physical distancing in dining areas', 'staylodgic' ),
		'5184' => __( 'In-room dining options available', 'staylodgic' ),
		'5185' => __( 'Staff follow all safety protocols as directed by local authorities', 'staylodgic' ),
		'5186' => __( 'Shared stationery such as printed menus, magazines, pens, and paper removed', 'staylodgic' ),
		'5187' => __( 'Hand sanitizer in guest accommodation and key areas', 'staylodgic' ),
		'5188' => __( 'Process in place to check the health of guests', 'staylodgic' ),
		'5189' => __( 'First aid kit available', 'staylodgic' ),
		'5190' => __( 'Contactless check-in/out', 'staylodgic' ),
		'5191' => __( 'Cashless payment available', 'staylodgic' ),
		'5192' => __( 'Physical distancing following guidelines from local authorities', 'staylodgic' ),
		'5193' => __( 'Mobile app for room service', 'staylodgic' ),
		'5194' => __( 'Screens or physical barriers placed between staff and guests in appropriate areas', 'staylodgic' ),
		'5195' => __( 'Property is cleaned by professional cleaning companies', 'staylodgic' ),
		'5196' => __( 'All plates, cutlery, glasses, and other tableware have been sanitized', 'staylodgic' ),
		'5197' => __( 'Guest accommodation cleaning can be avoided on request', 'staylodgic' ),
		'5198' => __( 'Invoices Provided', 'staylodgic' ),
		'5199' => __( 'Breakfast takeaway containers', 'staylodgic' ),
		'5200' => __( 'Delivered food is securely covered', 'staylodgic' ),
		'5201' => __( 'Access to healthcare professionals', 'staylodgic' ),
		'5202' => __( 'Thermometers for guests provided by the property', 'staylodgic' ),
		'5203' => __( 'Face masks for guests available', 'staylodgic' ),
		'5204' => __( 'Wild (non-domesticated) animals are not harmed at the property', 'staylodgic' ),
		'5205' => __( 'Recycling bins are available to guests, and waste is recycled', 'staylodgic' ),
		'5206' => __( 'At least 80% of food is sourced from the region', 'staylodgic' ),
		'5207' => __( 'At least 80% of lighting uses energy-efficient LED bulbs', 'staylodgic' ),
		'5208' => __( 'Only using water-efficient toilets', 'staylodgic' ),
		'5209' => __( 'Only using water-efficient showers', 'staylodgic' ),
		'5210' => __( 'All windows are double-glazed', 'staylodgic' ),
		'5211' => __( 'Food waste policy in place that includes education, food waste prevention, reduction, recycling, and disposal', 'staylodgic' ),
		'5212' => __( 'Investing a percentage of revenue back into community projects or sustainability projects', 'staylodgic' ),
		'5213' => __( 'Compensate for at least 10% of total annual carbon emissions by purchasing certified carbon offsets', 'staylodgic' ),
		'5214' => __( 'Tours and activities organized by local guides and businesses offered', 'staylodgic' ),
		'5215' => __( 'Vegetarian options available at the property', 'staylodgic' ),
		'5216' => __( 'Vegan options available at the property', 'staylodgic' ),
		'5217' => __( 'Green spaces such as gardens/rooftop gardens on the property', 'staylodgic' ),
		'5218' => __( 'At least 80% of the food provided is organic', 'staylodgic' ),
		'5219' => __( '100% renewable electricity is used throughout the property', 'staylodgic' ),
		'5220' => __( 'Local artists are offered a platform to display their talents', 'staylodgic' ),
		'5221' => __( 'Provide guests with information regarding local ecosystems, heritage, and culture, as well as visitor etiquette', 'staylodgic' ),
		'6000' => __( 'Lunch', 'staylodgic' ),
		'6001' => __( 'Dinner', 'staylodgic' ),
	);

	return $amenities;
}
